-- MySQL Script generated by MySQL Workbench
-- ma 17. lokakuuta 2016 23.14.46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wordSystem
-- -----------------------------------------------------
-- Database for online word training system for Vaadin course.
DROP SCHEMA IF EXISTS `wordSystem` ;

-- -----------------------------------------------------
-- Schema wordSystem
--
-- Database for online word training system for Vaadin course.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordSystem` DEFAULT CHARACTER SET utf8 ;
USE `wordSystem` ;

-- -----------------------------------------------------
-- Table `wordSystem`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordSystem`.`user` ;

CREATE TABLE IF NOT EXISTS `wordSystem`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT COMMENT 'User id',
  `date` DATE NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
COMMENT = 'Table representing the user of the system';


-- -----------------------------------------------------
-- Table `wordSystem`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordSystem`.`language` ;

CREATE TABLE IF NOT EXISTS `wordSystem`.`language` (
  `idLanguage` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLanguage`))
ENGINE = InnoDB
COMMENT = 'Table which represents a language in the system which words can be referenced to.';


-- -----------------------------------------------------
-- Table `wordSystem`.`word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordSystem`.`word` ;

CREATE TABLE IF NOT EXISTS `wordSystem`.`word` (
  `idWord` INT NOT NULL AUTO_INCREMENT,
  `idMaster` INT NULL DEFAULT NULL,
  `idLang` INT NOT NULL,
  `word` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idWord`),
  INDEX `fk_language_idx` (`idLang` ASC),
  INDEX `fk_masterWord_idx` (`idMaster` ASC),
  CONSTRAINT `fk_masterWord`
    FOREIGN KEY (`idMaster`)
    REFERENCES `wordSystem`.`word` (`idWord`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_language`
    FOREIGN KEY (`idLang`)
    REFERENCES `wordSystem`.`language` (`idLanguage`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The table which represents a word in the dictionary. A word can be of any language and it\'s linked to it\'s explanation/master word in Finnish.';


-- -----------------------------------------------------
-- Table `wordSystem`.`list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordSystem`.`list` ;

CREATE TABLE IF NOT EXISTS `wordSystem`.`list` (
  `idList` INT NOT NULL AUTO_INCREMENT,
  `creator` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT 'unnamedList',
  PRIMARY KEY (`idList`),
  INDEX `fk_creator_idx` (`creator` ASC),
  CONSTRAINT `fk_creator`
    FOREIGN KEY (`creator`)
    REFERENCES `wordSystem`.`user` (`idUser`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'List which is a composition of word entries which the user can train with.';


-- -----------------------------------------------------
-- Table `wordSystem`.`wordEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordSystem`.`wordEntry` ;

CREATE TABLE IF NOT EXISTS `wordSystem`.`wordEntry` (
  `idWord` INT NOT NULL,
  `idList` INT NOT NULL,
  PRIMARY KEY (`idWord`, `idList`),
  INDEX `fk_list_idx` (`idList` ASC),
  CONSTRAINT `fk_list`
    FOREIGN KEY (`idList`)
    REFERENCES `wordSystem`.`list` (`idList`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_word`
    FOREIGN KEY (`idWord`)
    REFERENCES `wordSystem`.`word` (`idWord`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Word entry in a list, relation between word and a list';


-- -----------------------------------------------------
-- Table `wordSystem`.`result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordSystem`.`result` ;

CREATE TABLE IF NOT EXISTS `wordSystem`.`result` (
  `idResult` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `idUser` INT NOT NULL,
  `score` INT NULL DEFAULT 0,
  `idLang` INT NOT NULL,
  `playTime` INT NULL DEFAULT -1,
  PRIMARY KEY (`idResult`),
  INDEX `fk_lang_idx` (`idLang` ASC),
  INDEX `fk_user_idx` (`idUser` ASC),
  CONSTRAINT `fk_lang`
    FOREIGN KEY (`idLang`)
    REFERENCES `wordSystem`.`language` (`idLanguage`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `wordSystem`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A result from a single run of the game, used for tracking user\'s progress';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
