package web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CreateList extends VerticalLayout {
    protected HorizontalLayout nameField;
    protected TextField listnameField;
    protected NativeSelect languageSelect;
    protected Button resetButton;
    protected Button addButton;
    protected Button removeButton;
    protected Button saveButton;
    protected Button createWordButton;
    protected Grid wordGrid;

    public CreateList() {
        Design.read(this);
    }
}
