package web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GameView extends VerticalLayout {
    protected Label wordLabel;
    protected Label numberLabel;
    protected TextField answerInput;
    protected Button submitButton;
    protected ProgressBar timeleft;

    public GameView() {
        Design.read(this);
    }
}
