package web;

import com.vaadin.ui.TabSheet;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
public class MainPage extends TabSheet {

    private ContentProvider provider;

    public MainPage(ContentProvider provider) {
        super();
        this.provider = provider;
        Tab listTab = addTab(new ListChooserLayout(provider));
        Tab createListTab = addTab(new CreateListLayout());
        listTab.setCaption("Choose list");
        createListTab.setCaption("Create list");
    }

}
